// export.js — turn data/session.json into a structured whitepaper scaffold.
// Run after the session: `npm run export`. Produces data/whitepaper-<ts>.md.
// This is the "souvenir" skeleton; turning it into polished prose is a later step.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(__dirname, '..', 'data');
const state = JSON.parse(fs.readFileSync(path.join(DATA, 'session.json'), 'utf8'));

const noteById = new Map(state.notes.map((n) => [n.id, n]));
const themeById = new Map(state.themes.map((t) => [t.id, t]));
const dt = (n) => n.clean || n.text; // prefer the AI-tidied text in the whitepaper
const nodeLabel = (id) => (noteById.get(id) ? `“${trim(dt(noteById.get(id)), 80)}”` : themeById.get(id) ? `**${themeById.get(id).label}**` : id);
function trim(s, n) { return s && s.length > n ? s.slice(0, n) + '…' : s || ''; }
function attrib() { return ''; } // Chatham House rules — no provenance recorded

const L = [];
const p = (s = '') => L.push(s);

p(`# ${state.session.title}`);
p(`*Structured record generated by Loom · ${state.notes.length} notes · ${new Date().toISOString().slice(0, 16).replace('T', ' ')}*`);
p();
p('## Executive summary');
p('> _To be written from the structure below._');
p();

// Themes (anchors first, then emergent by size)
const anchors = state.themes.filter((t) => t.kind === 'anchor');
const emergent = state.themes.filter((t) => t.kind !== 'anchor').sort((a, b) => b.noteIds.length - a.noteIds.length);

p('## Themes');
for (const t of [...anchors, ...emergent]) {
  if (!t.noteIds.length) continue;
  p(`### ${t.label}${t.kind === 'anchor' ? '' : ''}`);
  if (t.summary) p(`_${t.summary}_\n`);
  for (const nid of t.noteIds) {
    const n = noteById.get(nid);
    if (n) p(`- ${trim(dt(n), 300)}${attrib(n)}  \`[${n.kind}]\``);
  }
  p();
}

// Bridging connections
if (state.bridges.length) {
  p('## Bridging connections');
  for (const b of state.bridges) {
    p(`- **${b.type}**: ${nodeLabel(b.source)} → ${nodeLabel(b.target)}`);
    if (b.rationale) p(`  - ${b.rationale}`);
  }
  p();
}

// Heuristics invoked
if (state.heuristicHits.length) {
  p('## Heuristics invoked');
  for (const h of state.heuristicHits) {
    const n = noteById.get(h.noteId);
    p(`### ${h.name}`);
    p(`> ${h.principle}`);
    if (h.why) p(`*Why here:* ${h.why}`);
    if (n) p(`*Prompted by:* “${trim(dt(n), 160)}”`);
    if (h.questions && h.questions.length) { p('*Questions it forces:*'); for (const q of h.questions) p(`- ${q}`); }
    p();
  }
}

// Fact-checks & boundary conditions
if (state.factChecks.length || state.boundaryConditions.length) {
  p('## Fact-checks & boundary conditions');
  for (const f of state.factChecks) {
    const n = noteById.get(f.noteId);
    p(`- **[${f.verdict}]** ${f.statement}`);
    if (f.detail) p(`  - ${f.detail}`);
    const b = state.boundaryConditions.find((x) => x.noteId === f.noteId);
    if (b) p(`  - ⟂ ${b.text}`);
    if (n) p(`  - _from:_ “${trim(dt(n), 120)}”`);
  }
  p();
}

// Generalised principles
if (state.generalisations.length) {
  p('## Principles distilled from anecdotes');
  for (const g of state.generalisations) {
    p(`- ${g.principle}${g.coheresWith && g.coheresWith.length ? `  _(coheres with: ${g.coheresWith.join(', ')})_` : ''}`);
  }
  p();
}

// Open questions
const openQ = state.notes.filter((n) => n.kind === 'question');
if (openQ.length) {
  p('## Open questions');
  for (const n of openQ) p(`- ${trim(dt(n), 240)}${attrib(n)}`);
  p();
}

// Raw appendix
p('---');
p('## Appendix — full note log');
for (const n of state.notes) {
  p(`- \`${n.ts.slice(11, 16)}\` ${trim(dt(n), 400)}${attrib(n)} \`[${n.kind}]\``);
}

const out = path.join(DATA, `whitepaper-${new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-')}.md`);
fs.writeFileSync(out, L.join('\n'));
console.log(`Wrote ${out}\n  ${state.notes.length} notes · ${emergent.length} emergent themes · ${state.bridges.length} bridges · ${state.heuristicHits.length} heuristics · ${state.factChecks.length} fact-checks`);
